In [3]:
import pandas as pd

In [4]:
# Load the dataset
file_path = "/content/marketing_campaign.csv"
df = pd.read_csv(file_path)

In [5]:
# Display the first few rows to understand the structure
df.head()

  ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse
0  5524\t1957\tGraduation\tSingle\t58138\t0\t0\t0...
1  2174\t1954\tGraduation\tSingle\t46344\t1\t1\t0...
2  4141\t1965\tGraduation\tTogether\t71613\t0\t0\...
3  6182\t1984\tGraduation\tTogether\t26646\t1\t0\...
4  5324\t1981\tPhD\tMarried\t58293\t1\t0\t19-01-2...

In [6]:
# Reload the dataset with tab separator
df = pd.read_csv(file_path, sep="\t")

# Display the first few rows again to confirm proper loading
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [7]:
# Check for missing values
missing_values = df.isnull().sum()

# Display columns with missing values
missing_values[missing_values > 0]

Income    24
dtype: int64

In [8]:
# Fill missing Income values with the median
df["Income"].fillna(df["Income"].median(), inplace=True)

# Remove duplicate rows, if any
df_before = df.shape[0]
df.drop_duplicates(inplace=True)
df_after = df.shape[0]
duplicates_removed = df_before - df_after

duplicates_removed

<ipython-input-8-04b3f3d73113>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Income"].fillna(df["Income"].median(), inplace=True)

0